In [27]:
from tensorflow import keras
import tensorflow as tf
from tensorflow.keras.datasets import cifar100
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import csv
from PIL import Image
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.metrics import binary_accuracy
import pandas as pd

tf.random.set_seed(15) # 1 tf 40 np = 32 tops
np.random.seed(40)

In [2]:
cd

C:\Users\ivann


c:\Users\ivann\anaconda3\envs\deep_learning\Lib\site-packages\IPython\core\magics\osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})
c:\Users\ivann\anaconda3\envs\deep_learning\Lib\site-packages\IPython\core\magics\osm.py:428: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [28]:
cd ".\Documents\School\8vo. Semestre\Deep Learning"

[WinError 3] The system cannot find the path specified: '.\\Documents\\School\\8vo. Semestre\\Deep Learning'
C:\Users\ivann\Documents\School\8vo. Semestre\Deep Learning


c:\Users\ivann\anaconda3\envs\deep_learning\Lib\site-packages\IPython\core\magics\osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})


In [29]:
images = []
target = []
with open('./Image_Processing/Image_Classifier/dataset_64x64.csv', newline='') as csvfile:
    dataset = csv.reader(csvfile, delimiter=',')
    for i, row in enumerate(dataset):
        if i > 0:
            if row[0] == 'landscape':

                # image
                image_path = f'./Dataset/dataset/landscape_dat/landscape_64x64_bw/{row[1]}'

            if row[0] == 'imagenet':

                # image
                image_path = f'./Dataset/dataset/imagenet/imagenet_64x64_bw/{row[1]}'

            image = Image.open(image_path)
            data = np.asarray(image)
            images.append(data)

            #classification target
            if row[2]=='siggraph_2016':
                target.append(0)
            elif row[2]=='larsson_2016':
                target.append(1)
            elif row[2]=='zhang_2016':
                target.append(2)
            elif row[2]=='ddcolor':
                target.append(3)
            else:
                print(row)
                x = input("Enter")

images = np.array(images)
target = np.array(target)

In [30]:
print(images.shape)
rgb_batch = np.repeat(images[..., np.newaxis], 3, -1)
print(rgb_batch.shape)
print(target.shape)

(15328, 64, 64)
(15328, 64, 64, 3)
(15328,)


In [31]:
X_train, X_test, y_train, y_test = train_test_split(rgb_batch, target, test_size=0.1, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.1, random_state=1)

In [32]:
X_train, X_val, X_test = X_train / 255., X_val / 255., X_test / 255.

In [33]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(12415, 64, 64, 3)
(1380, 64, 64, 3)
(1533, 64, 64, 3)


In [34]:
print(np.bincount(y_train))
print(len(y_train))

[6277 1395 1965 2778]
12415


In [35]:
X_train_equal = []
y_train_equal = []
ids = np.arange(12415)
for c in range(4):
    class_id = ids[y_train == c]
    choice = np.random.choice(class_id, 1395, replace=False)
    X_train_equal.append(X_train[choice])
    y_train_equal.append(y_train[choice])
X_train_equal = np.array(X_train_equal)
y_train_equal = np.array(y_train_equal)

In [36]:
y_train_equal = np.concatenate((y_train_equal))
X_train_equal = np.concatenate((X_train_equal))
print(y_train_equal.shape)
print(X_train_equal.shape)

(5580,)
(5580, 64, 64, 3)


In [37]:
print(np.bincount(y_val))
print(len(y_val))

[655 155 253 317]
1380


In [38]:
X_val_equal = []
y_val_equal = []
ids = np.arange(1380)
for c in range(4):
    class_id = ids[y_val == c]
    choice = np.random.choice(class_id, 155, replace=False)
    X_val_equal.append(X_val[choice])
    y_val_equal.append(y_val[choice])
X_val_equal = np.array(X_val_equal)
y_val_equal = np.array(y_val_equal)

In [39]:
y_val_equal = np.concatenate((y_val_equal))
X_val_equal = np.concatenate((X_val_equal))
print(y_val_equal.shape)
print(X_val_equal.shape)

(620,)
(620, 64, 64, 3)


In [40]:
print(np.bincount(y_test))
print(len(y_test))

[791 175 227 340]
1533


In [41]:
X_test_equal = []
y_test_equal = []
ids = np.arange(1533)
for c in range(4):
    class_id = ids[y_test == c]
    choice = np.random.choice(class_id, 175 , replace=False)
    X_test_equal.append(X_test[choice])
    y_test_equal.append(y_test[choice])
X_test_equal = np.array(X_test_equal)
y_test_equal = np.array(y_test_equal)

In [42]:
y_test_equal = np.concatenate((y_test_equal))
X_test_equal = np.concatenate((X_test_equal))
print(y_test_equal.shape)
print(X_test_equal.shape)

(700,)
(700, 64, 64, 3)
